fpo-api/Jenkinsfile, fpo-web/Jenkinsfile
=> Minor pipeline updates

fpo-pdf/README.md
=> Update document reference.

fpo-web/package.json, fpo-web/src/app/app.module.ts, fpo-web/src/app/survey/recaptcha.service.ts, fpo-web/src/app/survey/survey.component.html, fpo-web/src/app/survey/survey.component.ts, fpo-web/src/index.html
To test this, on localhost.
Register here : http://www.google.com/recaptcha/admin with domain: localhost and this will provide new Site_key and secret_key.
=> [VTH-16] Adding recaptcha v2 checkbox

fpo-api/fpo_api/views.py, fpo-api/requirements.txt, fpo-pdf/templates/notice-to-disputant-response.html
This was an attempt to get the [BCSans](https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/bc-sans) font integrated into the form. This would allow future forms to print First Nations characters. 
I ran into issues with Weasyprint and it's dependencies.
**Future Approach** - I think the easiest approach will be to install the font into the fpo_pdf container. Abandon installing weasyprint within fpo_api.
All this logic needs to be commented out for the API to work properly. Will revisit in the future.
=> Commenting out all custom font logic

docker/docker-compose.yml, docker/manage.sh, fpo-web/openshift/angular-on-nginx-deploy.dev.param, fpo-web/openshift/angular-on-nginx-deploy.param, fpo-web/openshift/angular-on-nginx-deploy.prod.param, fpo-web/openshift/angular-on-nginx-deploy.test.param, fpo-web/openshift/templates/angular-on-nginx/angular-on-nginx-deploy.yaml, fpo-web/openshift/templates/nginx-runtime/nginx.conf.template, fpo-web/openshift/templates/nginx-runtime/s2i/bin/run
- Add support for better control over the application path (base href).
- Integrate proxy template and runtime setup from https://github.com/bcgov/aries-vcr
=> Update proxy configuration.

fpo-web/src/app/admin/admin.component.ts, fpo-web/src/app/survey/primary.component.ts
=> Fix for relative url for previewing PDF

docker/manage.sh
- Loads the fixtures (sample data) into the application.
=> Add loadFixtures command to manage script

fpo-api/api/pdf.py, fpo-api/api/send_email.py, fpo-api/api/views/SubmitTicketResponseView.py, fpo-api/templates/notice-to-disputant-response.html, fpo-api/templates/violation-ticket-statement-and-written-reasons.html, fpo-web/package.json, fpo-web/src/app/survey/survey.component.ts, fpo-web/src/assets/survey-primary.json
In last pull request I made some UI changes to ticketNumber field but forgot to update pdf generation templates.
So i fixed that and also made some other changes Andrew mentioned in last pull request.
=> Fix for last pull request, made changes for ticketNumber field.

fpo-api/fpo_api/settings.py, fpo-web/openshift/templates/nginx-runtime/nginx.conf.template, fpo-web/openshift/templates/nginx-runtime/s2i/bin/run
=> Fix proxy settings for api static files.

fpo-api/fpo_api/settings.py, fpo-web/openshift/templates/nginx-runtime/s2i/bin/run
- To work with path based proxies.
=> Update proxy settings for api static files.

fpo-api/openshift/templates/django/django-deploy.yaml
=> Fix api health check

fpo-api/openshift/templates/django/django-deploy.overrides.sh, fpo-api/openshift/templates/django/django-deploy.yaml
=> Add support for OIDC configuration.

fpo-web/src/app/survey/survey.component.html, fpo-web/src/app/survey/survey.component.ts
To perform form validation & check if current page has errors
=> Add submit button to submit the form and change complete button 

fpo-api/api/admin.py
Add location / region to Django Admin, this will make it easier to manage additional locations / region changes.
=> Add location / region to Django Admin

fpo-api/api/views/TicketResponseView.py, fpo-web/src/app/admin/admin-data.service.ts, fpo-web/src/app/admin/admin.component.html, fpo-web/src/app/admin/admin.component.scss
Ordering should only work by date now, instead of datetime. 
Small CSS tweaks for loader bar, View and Delete buttons.
=> Small ordering fix, small CSS changes

fpo-web/src/app/admin/admin-data.service.ts, fpo-web/src/app/admin/admin.component.html, fpo-web/src/app/admin/admin.component.ts, fpo-web/src/app/app.component.html
Fix tooltip causing overflow.
Hide new footer-detail.
Get rid of inbox, contact, logout links.
Fix blob handling for edge.
Fix date handling for edge.
=> Inbox fixes

fpo-api/api/views/TicketResponseView.py, fpo-api/requirements.txt, fpo-web/src/app/admin/admin-data.service.ts, fpo-web/src/app/admin/admin.component.html, fpo-web/src/app/admin/admin.component.ts
Change ordering by to date+time.
Add time to created and archived.
Lock delete down to superuser only, only show for superuser.
Update old browser version warning for older browsers. (Older version of edge, that doesn't print nicely)
Small bugfix for filtering by date on New Response page.
=> Admin inbox fixes

fpo-web/openshift/templates/nginx-runtime/s2i/bin/run
- Increase proxy buffer size to fix an issue calling back to the api while authenticating.
=> Update proxy buffer size

fpo-api/api/feedback.py
=> Fix issue with more than one recipient email address.

fpo-api/api/views/TicketResponseView.py
Special condition needed for date.
=> Special condition needed for date.

fpo-api/fpo_api/__init__.py, fpo-api/fpo_api/admin_timezone_middleware.py, fpo-api/fpo_api/settings.py, fpo-web/src/environments/environment.prod.ts
Fix for Matomo, and correct timezone for admin page
=> Matomo, and correct timezone for admin page

fpo-api/api/auth.py, fpo-api/fpo_api/settings.py, fpo-api/requirements.txt
I managed to create a new form + test out the admin functionality and it still seemed to work.
=> Django upgrade
